import concurrent.futures
from openrouter_client import ask_openrouter

class AdvancedOrchestrator:
    def __init__(self):
        self.primary_thinker = "llama" # Llama 3 70B for reasoning
        self.specialists = {
            "coder": "claude",        # Claude 3 Opus for coding
            "researcher": "gpt4",      # GPT-4o for accurate facts
            "summarizer": "gemma",      # Gemma 2 for speed
            "critic": "mistral"        # Mixtral for objective review
        }

    def analyze_intent(self, query):
        system_prompt = "You are an Intent Analyzer. Categorize the user's query into one of: 'coding', 'research', 'creative', 'simple_chat', or 'synthesis'. Return ONLY the category name."
        intent = ask_openrouter(query, model_alias=self.primary_thinker, system_prompt=system_prompt)
        return intent.strip().lower()

    def powerful_solve(self, query):
        intent = self.analyze_intent(query)
        print(f"Detected Intent: {intent}")

        if intent == "coding":
            # Round 1: Coding agent generates code
            code = ask_openrouter(query, model_alias=self.specialists["coder"])
            # Round 2: Critic agent reviews and fixes code
            review_prompt = f"Original Query: {query}\n\nGenerated Code:\n{code}\n\nReview this code for bugs and security issues. Return the improved final version."
            final_result = ask_openrouter(review_prompt, model_alias=self.specialists["critic"])
            return {"intent": intent, "result": final_result, "process": "Generated by Claude -> Reviewed by Mistral"}

        elif intent == "research":
            # Multi-model convergence
            with concurrent.futures.ThreadPoolExecutor() as executor:
                future_gpt = executor.submit(ask_openrouter, query, model_alias=self.specialists["researcher"])
                future_llama = executor.submit(ask_openrouter, query, model_alias=self.primary_thinker)
                
                res_gpt = future_gpt.result()
                res_llama = future_llama.result()

            # Synthesis
            synth_prompt = f"Synthesize these two research reports into a single powerful answer:\n\nReport 1: {res_gpt}\n\nReport 2: {res_llama}"
            final_result = ask_openrouter(synth_prompt, model_alias=self.primary_thinker)
            return {"intent": intent, "result": final_result, "process": "GPT-4 & Llama-3 Parallel Research -> Llama-3 Synthesis"}

        elif intent == "synthesis":
            # Large scale synthesis
            return self.ensemble_reasoning(query)

        else:
            # Standard high-quality response
            result = ask_openrouter(query, model_alias=self.primary_thinker)
            return {"intent": intent, "result": result, "process": "Llama-3 Reasoning"}

    def ensemble_reasoning(self, query):
        """Runs 3 models in parallel and has a judge choose the best."""
        models_to_test = ["llama", "mistral", "gemma"]
        
        with concurrent.futures.ThreadPoolExecutor() as executor:
            responses = list(executor.map(lambda m: ask_openrouter(query, model_alias=m), models_to_test))

        judge_prompt = f"User Question: {query}\n\nResponse A: {responses[0]}\n\nResponse B: {responses[1]}\n\nResponse C: {responses[2]}\n\nAs a Judge, select the best parts of each or choose the most accurate one to create the ultimate response."
        final_result = ask_openrouter(judge_prompt, model_alias="gpt4")
        
        return {"intent": "ensemble", "result": final_result, "process": "Three-way parallel execution -> GPT-4o Judgment"}

if __name__ == "__main__":
    orchestrator = AdvancedOrchestrator()
    print("Testing Powerful Solve for Research...")
    response = orchestrator.powerful_solve("Explain the future of quantum computing in medicine")
    print(f"Result:\n{response['result']}")
    print(f"Process: {response['process']}")
